Repository sculkmp/Sculk, pull requests merged in 2024-08, with the labels that each got.

#17 style(file header): Sculk-MP -> Sculk
  .idea/fileTemplates/includes/File Header.java
  src/main/java/org/sculk/Player.java
  src/main/java/org/sculk/Sculk.java
  src/main/java/org/sculk/SculkModule.java
  src/main/java/org/sculk/Server.java
  src/main/java/org/sculk/config/Config.java
  src/main/java/org/sculk/config/ConfigSection.java
  src/main/java/org/sculk/console/ConsoleThread.java
  src/main/java/org/sculk/console/TerminalConsole.java
  src/main/java/org/sculk/event/Cancellable.java
  src/main/java/org/sculk/event/Event.java
  src/main/java/org/sculk/event/EventFireHandler.java
  src/main/java/org/sculk/event/EventManager.java
  src/main/java/org/sculk/event/EventManagerInterface.java
  src/main/java/org/sculk/event/EventPriority.java
  src/main/java/org/sculk/event/Listener.java
  src/main/java/org/sculk/event/player/PlayerAsyncPreLoginEvent.java
  src/main/java/org/sculk/event/player/PlayerCreationEvent.java
  src/main/java/org/sculk/event/player/PlayerEvent.java
  src/main/java/org/sculk/event/player/PlayerPreLoginEvent.java
  src/main/java/org/sculk/exception/EventException.java
  src/main/java/org/sculk/exception/TaskException.java
  src/main/java/org/sculk/network/AdvancedSourceInterface.java
  src/main/java/org/sculk/network/BedrockInterface.java
  src/main/java/org/sculk/network/EventLoops.java
  src/main/java/org/sculk/network/Network.java
  src/main/java/org/sculk/network/SourceInterface.java
  src/main/java/org/sculk/network/packets/LoginPacketHandler.java
  src/main/java/org/sculk/network/protocol/ProtocolInfo.java
  src/main/java/org/sculk/player/PlayerInterface.java
  src/main/java/org/sculk/player/PlayerLoginData.java
  src/main/java/org/sculk/player/client/ClientChainData.java
  src/main/java/org/sculk/player/client/LoginChainData.java
  src/main/java/org/sculk/player/skin/Skin.java
  src/main/java/org/sculk/player/skin/data/ImageData.java
  src/main/java/org/sculk/player/skin/data/PersonaPiece.java
  src/main/java/org/sculk/player/skin/data/PersonaPieceTint.java
  src/main/java/org/sculk/player/skin/data/SkinAnimation.java
  src/main/java/org/sculk/scheduler/AsyncTask.java
  src/main/java/org/sculk/scheduler/Scheduler.java
  src/main/java/org/sculk/scheduler/Task.java
  src/main/java/org/sculk/scheduler/TaskHandler.java
  src/main/java/org/sculk/thread/ThreadStore.java
  src/main/java/org/sculk/timings/JsonUtil.java
  src/main/java/org/sculk/utils/Identifiers.java
  src/main/java/org/sculk/utils/SkinUtils.java
  src/main/java/org/sculk/utils/TextFormat.java
  src/main/java/org/sculk/utils/Utils.java
  src/main/java/org/sculk/world/WorldManager.java
Labels: Priority: Low

#18 feat(server-properties): Creation of ServerProperties System
  src/main/java/org/sculk/Server.java
  src/main/java/org/sculk/config/ServerProperties.java
  src/main/java/org/sculk/config/ServerPropertiesKeys.java
Labels: Priority: Low, Status: Incomplete, Category: Core

#20 Readme Update
  .gitignore
  README.md
Labels: Priority: Low, Status: Awaiting Review

#21 Implement Forms
  src/main/java/org/sculk/Player.java
  src/main/java/org/sculk/event/player/PlayerFormRespondedEvent.java
  src/main/java/org/sculk/form/Form.java
  src/main/java/org/sculk/form/defaults/CustomForm.java
  src/main/java/org/sculk/form/defaults/ModalForm.java
  src/main/java/org/sculk/form/defaults/SimpleForm.java
  src/main/java/org/sculk/form/element/Element.java
  src/main/java/org/sculk/form/element/ElementDropdown.java
  src/main/java/org/sculk/form/element/ElementInput.java
  src/main/java/org/sculk/form/element/ElementLabel.java
  src/main/java/org/sculk/form/element/ElementSlider.java
  src/main/java/org/sculk/form/element/ElementStepSlider.java
  src/main/java/org/sculk/form/element/ElementToggle.java
  src/main/java/org/sculk/form/element/button/ElementButton.java
  src/main/java/org/sculk/form/element/button/Image.java
  src/main/java/org/sculk/form/response/CustomResponse.java
  src/main/java/org/sculk/form/response/ElementResponse.java
  src/main/java/org/sculk/form/response/ModalResponse.java
  src/main/java/org/sculk/form/response/Response.java
  src/main/java/org/sculk/form/response/SimpleResponse.java
  src/main/java/org/sculk/utils/json/Serializable.java
Labels: Status: Incomplete, Type: Todo, Category: API

#22 Implement PluginManager & Plugin
  pom.xml
  src/main/java/org/sculk/Server.java
  src/main/java/org/sculk/plugin/Plugin.java
  src/main/java/org/sculk/plugin/PluginClassLoader.java
  src/main/java/org/sculk/plugin/PluginData.java
  src/main/java/org/sculk/plugin/PluginLoader.java
  src/main/java/org/sculk/plugin/PluginManager.java
Labels: Priority: High, Type: Todo, Category: Core

#23 Implement plugin api version check
  src/main/java/org/sculk/plugin/Plugin.java
  src/main/java/org/sculk/plugin/PluginClassLoader.java
  src/main/java/org/sculk/plugin/PluginData.java
  src/main/java/org/sculk/plugin/PluginLoader.java
  src/main/java/org/sculk/plugin/PluginManager.java
Labels: Priority: Medium, Type: Todo, Category: Core, Category: API
